### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Thaz09**

### CODE REVIEW

**Review by rossfcowie — CHANGES_REQUESTED** [review]
not memey enough

**Comment by ecoutoo** [comment]
I dont trust this guy. Request denied

**Review by TomHoey — COMMENTED** [review]
Not enough stonks for me... Get your Gamestop stock in, then follow up with some AMC stock and then I will approve this.

**Review by TomBraggg — APPROVED** [review]
lets go

**Review by TomBraggg — COMMENTED** [review]
lets go

**Review by Thaz09 — COMMENTED** [review]
Accepted!!

**Pull request merged**
